### ISSUE TITLE
Don't limit support for node >9

### ISSUE THREAD

**Issue by ritave** [mweibel/lcov-result-merger#38]
Node is at v10 now.

Lcov-result-merger blocks the whole build due to it's limitation in package.json to node versions <= 9.

I imagine this tool still works with the newest version of node, please remove the artificial limit

**Comment by mweibel** [comment]
You’re more than welcome to submit a pr.

**Comment by mweibel** [comment]
I added a PR for this, once travis says that's ok I'll publish a new release.

@ritave I'm doing this project in my free time. The issue you opened is valid, but I'd welcome a friendlier tone the next time. 
Also during the time you've written that issue you could already have opened a PR changing the requirements which would have helped everyone.
Please consider this the next time, thanks.

**Comment by ritave** [comment]
@mweibel My bad, it was not my intention to make it sound harsh.
I had some time to work on this today - seems we've both added a PR. Additionally found a bug due to carriage returns.

**Comment by mweibel** [comment]
@ritave thanks! I merged yours now, as mine is failing because there's an issue with node 10.2.0 atm. 
As you've seen, this and some other fixes should be released as version 3 now. 👍
