### ISSUE TITLE
BRDA parsing doesn't follow lcov spec

### ISSUE THREAD

**Issue by smspillaz** [mweibel/lcov-result-merger#4]
The lcov 'spec' (which is really just a manpage) says that '-' is a valid value for the fourth token in a `BRDA` line. It means "code containing branch was never executed, so branch could never have ben taken" as opposed to "branch not taken". Certain coverage tools like `geninfo` will output "-". This confuses `lcov-result-merger` into thinking that the branch hit total is `NaN`.

See the [relevant section](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php):

    Branch coverage information is stored which one line per branch:

          BRDA:<line number>,<block number>,<branch number>,<taken>

        Block number and branch number are gcc internal  IDs  for  the  branch.
        Taken  is either ’-’ if the basic block containing the branch was never
        executed or a number indicating how often that branch was taken.

        Branch coverage summaries are stored in two lines:

          BRF:<number of branches found>
          BRH:<number of branches hit>

**Comment by mweibel** [comment]
Fixed with #5
