### ISSUE TITLE
File Patterns

### ISSUE THREAD

**Issue by quiin** [mweibel/lcov-result-merger#43]
What kind of patterns are supported? I'm trying to merge `lcov.info` files on 2 different directories using the following pattern on stdout:
`/app/static_build/coverage_reports/frontend/**/lcov.info`

**Comment by mweibel** [comment]
please elaborate on your issues. Specify input, output, what happened. E.g. in this case my immediate questions where:
> and what's the result of that trying? does it work or not? what's the output?

anyhow, to the other questions: lcov-result-merger uses [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs) which uses [`node-glob`](https://github.com/isaacs/node-glob) for globbing. 

If it doesn't work it might be that your shell already does an expansion and therefore `lcov-result-merger` doesn't receive the glob. [You could try quoting or escaping it.](https://github.com/mweibel/lcov-result-merger/blob/master/bin/lcov-result-merger.js)

To see what's happening, a few console.logs always help. You could add a `console.log(process.argv)` e.g. in [bin/lcov-result-merger](https://github.com/mweibel/lcov-result-merger/blob/master/bin/lcov-result-merger.js) and see what happens.
