### ISSUE TITLE
Coverage data lost when combining

### ISSUE THREAD

**Issue by mlewand** [mweibel/lcov-result-merger#45]
Thanks for sharing the lib. Before incorporating I wanted to give it a simple try to ensure that everything works fine.

Here either I'm missing something, or the results are corrupted during the merge. Repro steps are simple, just exec couple of commands:

*   `wget https://gist.githubusercontent.com/mlewand/6ad97f21f07ce1e215f9565f7cefa4ad/raw/b8a39cdc544a17acddc9516a32fb2a3ee1dd284c/lcov.info && touch combined_lcov.info`
*   `npx lcov-result-merger lcov.info combined_lcov.info`
*   `diff lcov.info combined_lcov.info`

### Expected

The two files should be equal (diff should not print any output).

### Actual

Files are different.

### Other information

Based on path you can see that it has been executed on Windows (10) os.

**Comment by mweibel** [comment]
thanks for the repro case. The reason for this issue is #14. PRs welcome :) 
Gonna close this issue therefore.
