### ISSUE TITLE
Ongoing Releases

### ISSUE THREAD

**Issue by mdeanjones** [mweibel/lcov-result-merger#49]
@mweibel would you like to retain publishing control for the repository?

**Comment by mweibel** [comment]
@mdeanjones hey! I think for the first few releases I'm going to retain publishing control and check the diffs quickly. Afterwards I'll be handing that over to you. Does that sound fine to you?

**Comment by mweibel** [comment]
just let me know when you want to release (and possibly already create the tags and the change in package.json) and notify me about it - I'll handle the rest.

**Comment by mdeanjones** [comment]
That sounds fine to me @mweibel, and in which case I believe that 3.3.0 is ready.

https://github.com/mweibel/lcov-result-merger/compare/f0fe86582adccb59e8ad9c77236a8978d493e5c0..master
