### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by hugobessa** [mweibel/lcov-result-merger#51]
Do we have plans for rolling the next release? Is there any blocker? Any help wanted?

We have breaking changes like dependency updates and dropping support to older versions on Node. Should we bump it to 4.0.0?

**Comment by mdeanjones** [comment]
Thanks for the reminder @hugobessa. We'll need to summon the keeper of the keys, @mweibel, to perform the necessary ceremonies.

This definitely warrants a major bump to 4.0.

**Comment by mweibel** [comment]
@mdeanjones running tests locally and one failed:
```
 2 passing (183ms)
  1 failing

  1) lcovResultMerger CLI
       should optionally prepend source file lines with corrected pathing:

      AssertionError: expected 'SF:./test/fixtures/coverage-subfolder…' to equal 'SF:./test/fixtures/coverage-subfolder…'
      + expected - actual

      -SF:./test/fixtures/coverage-subfolder/b/src/index.js
      +SF:./test/fixtures/coverage-subfolder/a/src/index.js
       DA:1,1
       end_of_record
      -SF:./test/fixtures/coverage-subfolder/b/src/Foo.js
      +SF:./test/fixtures/coverage-subfolder/a/src/Foo.js
       DA:1,1
       DA:4,1
       DA:5,17
       DA:8,8
--
       DA:28,8
       DA:33,1
       DA:34,9
       DA:37,1
      -BRDA:24,1,0,2
      +BRDA:24,1,0,-
       BRDA:24,1,1,8
       BRDA:24,1,2,-
       end_of_record
      -SF:./test/fixtures/coverage-subfolder/a/src/index.js
      +SF:./test/fixtures/coverage-subfolder/b/src/index.js
       DA:1,1
       end_of_record
      -SF:./test/fixtures/coverage-subfolder/a/src/Foo.js
      +SF:./test/fixtures/coverage-subfolder/b/src/Foo.js
       DA:1,1
       DA:4,1
       DA:5,17
       DA:8,8
--
       DA:28,8
       DA:33,1
       DA:34,9
       DA:37,1
      -BRDA:24,1,0,-
      +BRDA:24,1,0,2
       BRDA:24,1,1,8
       BRDA:24,1,2,-
       end_of_record

      at Context.<anonymous> (test/lcov-result-merger-cmd-spec.js:71:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

could you please double-check?

**Comment by mdeanjones** [comment]
Looking now @mweibel; I can reproduce locally as well. First impression is that there's a change in the newline character(s), but I'm not quite sure. Something subtle is definitely different between Ubuntu and OSX.

**Comment by hugobessa** [comment]
I'll see what I can do. Unfortunately, I don't have access to OSX to reproduce the issue and debug.

**Comment by WikiRik** [comment]
I think this test is flaky on Ubuntu (maybe others as well). Or could you consistently reproduce this issue?

**Comment by dzzk** [comment]
Do not know how it was before but if you need MacOS guy - here I am.

`"lcov-result-merger": "^3.3.0"`

I did not provide correct glob for search on start,
since I did supposed I'm in a right place.

My report is below:

```
 yarn lcov-result-merger lcov.info outFile.lcov
yarn run v1.22.19
$ ../Users/../node_modules/.bin/lcov-result-merger lcov.info outFile.lcov
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/../lcov.info (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/../node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:514:26)
    at Glob.emit (node:events:394:28)
    at Glob._finish (/Users/../node_modules/glob/glob.js:194:8)
    at done (/Users/../node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/Users/../node_modules/glob/glob.js:685:12)
    at /Users/../node_modules/glob/glob.js:673:10
    at Glob._stat2 (/Users/../node_modules/glob/glob.js:769:12)
    at lstatcb_ (/Users/../node_modules/glob/glob.js:761:12)
    at RES (/Users/../node_modules/inflight/inflight.js:31:16)
Emitted 'error' event on DestroyableTransform instance at:
    at Pumpify.emit (node:events:394:28)
    at Pumpify.Duplexify._destroy (/Users/../node_modules/duplexify/index.js:191:15)
    at /Users/../node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Than I changed glob patter to right one:
 
 yarn lcov-result-merger coverage/**/lcov.info outFile.lcov
yarn run v1.22.19
$ /Users/../node_modules/.bin/lcov-result-merger coverage/integration/lcov.info outFile.lcov
✨  Done in 0.68s.
```

**Comment by mweibel** [comment]
thanks for the ping @dzzk. Not sure if you wanted to open a new issue though?

> I think this test is flaky on Ubuntu (maybe others as well). Or could you consistently reproduce this issue?

I tested again and it is indeed flaky. However, looking more closely at the test failure, I believe the reason is because the order of files in the result is not always the same. 
@hugobessa could this be because of the latest changes?

@mdeanjones not sure how you want to proceed - do you want to try fixing the test or do you want to ignore it for now and release version 4.0.0?

**Comment by hugobessa** [comment]
I've made many changes to the file processing part as I completely removed vinyl-fs as a dependence. So, yes, the latest change can be causing the flakiness. I'll try to reproduce the issue here and fix it.

**Comment by mdeanjones** [comment]
Sorry for the long silence @mweibel and @hugobessa; I've been away from my keyboard for awhile. Correct me if I am wrong, but I don't believe that the file order being non-deterministic would effect how the resulting LCOV is interpreted. That said, it'd be good to know if it is indeed the culprit.

I haven't worked with fast-glob much, but I am curious to see if its [concurrency](https://github.com/mrmlnc/fast-glob#concurrency) capability might have something to do with this. Will take a look today.

**Comment by mweibel** [comment]
no it shouldn't have an influence - fixing the test to ignore the order of files would be a viable option too IMO

**Comment by mdeanjones** [comment]
Not sure why I was stroking my chin so much - _"if it is indeed the culprit"_ - when the test output is really clear on that point. Maybe I came back from vacation too soon.

It looks like there are some small behavioral differences between `vinyl` and `fast-glob` that may be getting in the way here. `vinyl` File objects default to [an absolute path](https://github.com/gulpjs/vinyl#filepath), while `fast-glob`'s [do not](https://github.com/mrmlnc/fast-glob#absolute). Configuring fast-glob `{ absolute: true }` appears to clear the issue up on OSX.

https://github.com/mdeanjones/lcov-result-merger/blob/0d8f6a2e13fc6c3dcd16e830b9429248ed372b7d/bin/lcov-result-merger.js#L38

**Comment by mdeanjones** [comment]
> Not sure why I was stroking my chin so much - _"if it is indeed the culprit"_ - when the test output is really clear on that point. Maybe I came back from vacation too soon.
> 
> It looks like there are some small behavioral differences between `vinyl` and `fast-glob` that may be getting in the way here. `vinyl` File objects default to [an absolute path](https://github.com/gulpjs/vinyl#filepath), while `fast-glob`'s [do not](https://github.com/mrmlnc/fast-glob#absolute). Configuring fast-glob `{ absolute: true }` appears to clear the issue up on OSX.
> 
> https://github.com/mdeanjones/lcov-result-merger/blob/0d8f6a2e13fc6c3dcd16e830b9429248ed372b7d/bin/lcov-result-merger.js#L38

Never mind this. Run enough times and you'll still see `A <-> B` flip back and forth. The search continues.

**Comment by mweibel** [comment]
Release 4.0.0 is out. Thanks everyone.
